apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: usermanagementmicroservice
  name: usermanagementmicroservice
spec:
  ports:
  - port: 8500
    protocol: TCP
    targetPort: 8500
  selector:
    app: usermanagementmicroservice
status:
  loadBalancer: {}